spring:
  application:
    name: hello-server

server:
  port: 8071

eureka:
  client:
    registerWithEureka: true  #OPTIONAL
    fetchRegistry: true       #OPTIONAL
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost  #OPTIONAL